### ISSUE TITLE
data_collector failing with matplotlib

### ISSUE THREAD

**Issue by mopuru-murali** [juliojsb/sarviewer#5]
Generating matplotlib graphs (set graph_generator="matplotlib") using data_collector but failing with following error. I tried with both python2 and python3 versions.

	--> /dbc/blr-dbc301/mmopuru/anaconda2/bin/pip install matplotlib
	Requirement already satisfied: matplotlib in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages
	Requirement already satisfied: numpy>=1.7.1 in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)
	Requirement already satisfied: six>=1.10 in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)
	Requirement already satisfied: python-dateutil in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)
	Requirement already satisfied: functools32 in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)
	Requirement already satisfied: subprocess32 in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)
	Requirement already satisfied: pytz in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)
	Requirement already satisfied: cycler>=0.10 in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)
	Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages (from matplotlib)

	--> PATH=/dbc/blr-dbc301/mmopuru/anaconda2/bin:$PATH ./data_collector.sh
	Please specify the number of samples to take-> 5
	Please specify the sample interval (take sample every X seconds)-> 1
	Taking 5 samples with 1 seconds interval
	Total time to collect all data: 5 seconds
	----------------------------------
	>>> Collecting data
	>>> Please wait until data collection is completed
	----------------------------------
	- You can abort this script with Ctrl+C, but have in mind the data will stop being collected when you cancel it.
	- You will also need to manually launch script plotter.sh to generate the graphs.
	----------------------------------
	>>> Just 5 seconds more while processing all data
	----------------------------------
	Done!
	Traceback (most recent call last):
	  File "tasks.py", line 76, in <module>
		generate_graph()
	  File "tasks.py", line 52, in generate_graph
		t_blocked.append(row[6])
	IndexError: list index out of range
	Traceback (most recent call last):
	  File "netinterface.py", line 73, in <module>
		generate_graph()
	  File "netinterface.py", line 65, in generate_graph
		plt.savefig('../../graphs/netinterface.png', bbox_inches='tight')
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 697, in savefig
		res = fig.savefig(*args, **kwargs)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1573, in savefig
		self.canvas.print_figure(*args, **kwargs)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2200, in print_figure
		**kwargs)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 545, in print_png
		FigureCanvasAgg.draw(self)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
		self.figure.draw(self.renderer)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
		draw(artist, renderer, *args, **kwargs)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1144, in draw
		renderer, self, dsu, self.suppressComposite)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
		a.draw(renderer)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
		draw(artist, renderer, *args, **kwargs)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2426, in draw
		mimage._draw_list_compositing_images(renderer, self, dsu)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
		a.draw(renderer)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
		draw(artist, renderer, *args, **kwargs)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/axis.py", line 1136, in draw
		ticks_to_draw = self._update_ticks(renderer)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/axis.py", line 969, in _update_ticks
		tick_tups = [t for t in self.iter_ticks()]
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/axis.py", line 916, in iter_ticks
		for i, val in enumerate(majorLocs)]
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/dates.py", line 466, in __call__
		dt = num2date(x, self.tz)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/dates.py", line 401, in num2date
		return _from_ordinalf(x, tz)
	  File "/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/matplotlib/dates.py", line 254, in _from_ordinalf
		dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
	ValueError: ordinal must be >= 1

Note: I'm collecting sysstats for every 1 minute instead of default 10 mins interval

	--> sar
	Linux 2.6.32-358.23.2.el6.x86_64 (mmopuru-service.eng.vmware.com)       02/28/2018      _x86_64_        (4 CPU)

	12:00:01 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
	12:01:01 AM     all     10.20      0.00      2.54      0.00      0.00     87.26
	12:02:01 AM     all      9.81      0.00      2.41      0.00      0.00     87.77
	12:03:01 AM     all      9.92      0.00      2.44      0.01      0.00     87.64
	12:04:01 AM     all     10.06      0.00      2.50      0.01      0.00     87.42
	12:05:01 AM     all      9.81      0.00      2.40      0.03      0.00     87.76
	12:06:01 AM     all      9.82      0.00      2.49      0.01      0.00     87.67
	12:07:01 AM     all      9.98      0.00      2.42      0.00      0.00     87.59
	12:08:02 AM     all      9.87      0.00      2.44      0.00      0.00     87.69
	12:09:01 AM     all      9.99      0.00      2.44      0.00      0.00     87.57
	12:10:01 AM     all      9.86      0.00      2.47      0.00      0.00     87.66
	12:11:01 AM     all      9.92      0.00      2.47      0.01      0.00     87.60
	12:12:01 AM     all      9.80      0.00      2.47      0.00      0.00     87.72
	12:13:01 AM     all      9.94      0.00      2.48      0.00      0.00     87.57
	12:14:01 AM     all      9.92      0.00      2.43      0.01      0.00     87.64
	12:15:01 AM     all      9.97      0.00      2.44      0.02      0.00     87.58
	12:16:01 AM     all      9.81      0.00      2.41      0.00      0.00     87.78
	12:17:01 AM     all      9.96      0.00      2.40      0.01      0.00     87.63
	12:18:01 AM     all     10.09      0.00      2.40      0.01      0.00     87.50
	12:19:01 AM     all     10.07      0.00      2.46      0.01      0.00     87.46
	12:20:01 AM     all      9.92      0.00      2.42      0.00      0.00     87.65

**Comment by juliojsb** [comment]
As stated in the previous issue reported, it seems sysstat 10.1.5+ is needed for the scripts to work. Both gnuplot and matplotlib are looking for columns that sysstat 9.0.4 (default version in CentOS 6) is not generating.
